/* Design system: "精密工作台" — compact production controls for batch delivery, shared board templates, and diff sensitivity. */
import { useEffect, useState } from "react";

type Board = { id: string; name: string; artboard: { width: number; height: number } };
type BoardTemplate = { id: string; name: string; board: Board };
const emit = (name: string, detail?: unknown) => window.dispatchEvent(new CustomEvent(name, { detail }));

export default function ProductionToolsDock() {
  const [panel, setPanel] = useState<"export" | "templates" | "diff" | null>(null);
  const [boards, setBoards] = useState<Board[]>([]); const [templates, setTemplates] = useState<BoardTemplate[]>([]);
  const [threshold, setThreshold] = useState(42); const [opacity, setOpacity] = useState(88); const [naming, setNaming] = useState("{project}_{index}_{artboard}"); const [zip, setZip] = useState(true);
  useEffect(() => { const updateBoards = (event: Event) => setBoards((event as CustomEvent<{ boards: Board[] }>).detail.boards); const updateTemplates = (event: Event) => setTemplates((event as CustomEvent<BoardTemplate[]>).detail); window.addEventListener("logocraft-boards-updated", updateBoards); window.addEventListener("logocraft-board-templates-updated", updateTemplates); window.dispatchEvent(new Event("logocraft-boards-request")); window.dispatchEvent(new Event("logocraft-board-templates-request")); return () => { window.removeEventListener("logocraft-boards-updated", updateBoards); window.removeEventListener("logocraft-board-templates-updated", updateTemplates); }; }, []);
  useEffect(() => { document.documentElement.style.setProperty("--pixel-diff-opacity", `${opacity / 100}`); document.documentElement.style.setProperty("--pixel-diff-contrast", `${1 + threshold / 32}`); }, [opacity, threshold]);
  return <><div className="production-dock fixed bottom-[52px] left-[72px] z-40 hidden gap-1 xl:flex"><button className="action-button border border-white/10 bg-[#202023] px-2 text-[10px]" onClick={() => setPanel("export")}>导出</button><button className="action-button border border-white/10 bg-[#202023] px-2 text-[10px]" onClick={() => setPanel("templates")}>模板</button><button className="action-button border border-white/10 bg-[#202023] px-2 text-[10px]" onClick={() => setPanel("diff")}>Δ</button></div>
    {panel === "export" && <div className="production-float" role="dialog" aria-label="批量导出"><header><span className="section-label">批量交付</span><button onClick={() => setPanel(null)}>关闭</button></header><div className="p-3"><p className="text-[10px] leading-relaxed text-[#aaa9ac]">以命名规则输出 {boards.length} 个画板；可选单独下载或归档为一个 ZIP 文件。</p><label className="inspector-field mt-3"><span>命名规则</span><input value={naming} onChange={(event) => setNaming(event.target.value)} /><small className="text-[8px] text-[#808084]">{`{project} · {index} · {artboard} · {date}`}</small></label><label className="mt-3 flex items-center justify-between border-y border-white/10 py-2 text-[10px] text-[#c5c3c1]"><span>ZIP 归档下载</span><input type="checkbox" checked={zip} onChange={(event) => setZip(event.target.checked)} /></label><div className="mt-3 grid grid-cols-2 gap-2"><button className="action-button action-primary" onClick={() => emit("logocraft-batch-export", { format: "svg", naming, zip })}>{zip ? "ZIP · SVG" : "全部 SVG"}</button><button className="action-button" onClick={() => emit("logocraft-batch-export", { format: "png", naming, zip })}>{zip ? "ZIP · PNG" : "全部 PNG"}</button></div><div className="mt-3 divide-y divide-white/10 border-y border-white/10">{boards.map((board, index) => <div className="flex items-center justify-between py-2 text-[10px]" key={board.id}><span>{String(index + 1).padStart(2, "0")} · {board.name}</span><span className="technical-number text-[#818085]">{board.artboard.width}×{board.artboard.height}</span></div>)}</div></div></div>}
    {panel === "templates" && <div className="production-float" role="dialog" aria-label="共享画板模板"><header><span className="section-label">共享画板模板</span><button onClick={() => setPanel(null)}>关闭</button></header><div className="p-3"><div className="grid grid-cols-2 gap-2"><button className="action-button justify-start" onClick={() => { const name = window.prompt("将当前画板保存为共享模板", `画板模板 ${templates.length + 1}`); if (name?.trim()) emit("logocraft-board-template-save", name.trim()); }}>+ 保存模板</button><button className="action-button" onClick={() => emit("logocraft-board-template-import")}>导入 JSON</button></div><div className="mt-3 space-y-1">{templates.length ? templates.map((template) => <div className="template-instance" key={template.id}><button className="min-w-0 flex-1 truncate text-left" onClick={() => emit("logocraft-board-template-apply", template.id)}><strong>{template.name}</strong><small>{template.board.artboard.width}×{template.board.artboard.height} · 应用后新建画板</small></button><button title="导出模板" onClick={() => emit("logocraft-board-template-export", template.id)}>⇩</button><button aria-label="删除模板" onClick={() => emit("logocraft-board-template-delete", template.id)}>×</button></div>) : <p className="py-3 text-center text-[10px] text-[#838286]">尚未保存模板。模板会保留画板尺寸、图层、参考线与构造设置。</p>}</div></div></div>}
    {panel === "diff" && <div className="production-float" role="dialog" aria-label="差异图调节"><header><span className="section-label">历史差异精调</span><button onClick={() => setPanel(null)}>关闭</button></header><div className="space-y-4 p-3"><label className="range-control"><span><b>像素阈值</b><em>{threshold}%</em></span><input className="range-input" type="range" min="0" max="100" value={threshold} onChange={(event) => setThreshold(Number(event.target.value))} /></label><label className="range-control"><span><b>叠加透明度</b><em>{opacity}%</em></span><input className="range-input" type="range" min="10" max="100" value={opacity} onChange={(event) => setOpacity(Number(event.target.value))} /></label><p className="text-[9px] leading-relaxed text-[#838286]">在历史面板选定 A / B 快照后，阈值会增强可见的像素差异，透明度控制后景快照的叠加强度。</p></div></div>}
  </>;
}
