/* Component design: "精密工作台" — persistent local versions presented as a compact archival drawer. */
import { Clock3, Eye, RotateCcw, Save, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";

type SavedVersion = { id: string; name: string; createdAt: string; reason: "auto" | "manual"; thumbnail: string; layerCount: number };
const emit = (name: string, detail?: unknown) => window.dispatchEvent(new CustomEvent(name, { detail }));

export default function VersionHistoryPanel() {
  const [open, setOpen] = useState(false); const [versions, setVersions] = useState<SavedVersion[]>([]); const [previewId, setPreviewId] = useState<string | null>(null);
  useEffect(() => { const update = (event: Event) => setVersions((event as CustomEvent<SavedVersion[]>).detail); const show = () => setOpen(true); if (new URLSearchParams(window.location.search).has("versions")) setOpen(true); window.addEventListener("logocraft-version-list-updated", update); window.addEventListener("logocraft-versions-open", show); window.dispatchEvent(new Event("logocraft-version-list-request")); return () => { window.removeEventListener("logocraft-version-list-updated", update); window.removeEventListener("logocraft-versions-open", show); }; }, []);
  const preview = versions.find((version) => version.id === (previewId ?? versions[0]?.id));
  if (!open) return null;
  return <div className="version-scrim" role="dialog" aria-modal="true" aria-label="本地保存版本"><section className="version-panel"><header><div><p className="section-label">本地版本</p><h2>可恢复的自动存档</h2></div><button className="tool-button h-8 w-8" title="关闭版本列表" onClick={() => setOpen(false)}>×</button></header><div className="version-toolbar"><p>自动保存会保留最近 24 个版本；恢复后仍可继续编辑。</p><button className="action-button" title="立即创建手动快照" onClick={() => emit("logocraft-version-capture")}><Save size={13} /> 保存快照</button></div><div className="version-content"><div className="version-list">{versions.length ? versions.map((version) => <button key={version.id} className={`version-row ${preview?.id === version.id ? "version-row-active" : ""}`} onClick={() => setPreviewId(version.id)}><img src={version.thumbnail} alt={`${version.name} 缩略图`} /><span><strong>{version.name}</strong><small><Clock3 size={10} /> {new Date(version.createdAt).toLocaleString("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" })} · {version.layerCount} 层</small></span><em>{version.reason === "manual" ? "手动" : "自动"}</em></button>) : <p className="version-empty">尚未创建可恢复版本。继续编辑后，系统会自动归档当前工程。</p>}</div><div className="version-preview">{preview ? <><div className="version-preview-art"><img src={preview.thumbnail} alt={`${preview.name} 版本预览`} /></div><div className="mt-3 flex items-center justify-between"><span className="technical-number text-[9px] text-[#8d8b8f]">{preview.reason === "manual" ? "MANUAL SNAPSHOT" : "AUTO ARCHIVE"}</span><div className="flex gap-1"><button className="action-button h-8 px-2" title="恢复此版本" onClick={() => { emit("logocraft-version-restore", preview.id); setOpen(false); }}><RotateCcw size={13} /> 恢复</button><button className="action-button h-8 px-2" title="删除此版本" onClick={() => emit("logocraft-version-delete", preview.id)}><Trash2 size={13} /></button></div></div><p className="mt-2 text-[9px] leading-relaxed text-[#8b898d]">此预览来自本地工程快照；恢复会覆盖当前画布、画板、参考线和模板状态。</p></> : <div className="version-preview-empty"><Eye size={18} /> 选择一个版本以预览</div>}</div></div></section></div>;
}
